export const staticWords = {
  belong:
    "You mentioned the word 'belong'. Great job! It is important for students to know that they belong in a math class regardless of past math experiences and future mistakes and that you believe that they have the capacity to learn and improve throughout your course.",
  exam: "You mentioned 'exam'. While it is important to talk about the importance of mistakes and revisions, as it relates to examinations, it may also be beneficial to touch on the variety of reasons students perform poorly. If you haven't already, feel free to mention things like testing anxiety and lack of preparation in previous classes. In addition, don’t forget to include the types of strategies that students can use to improve their readiness for tests–including revisions, peer tutoring, meeting with you individually etc",
  exams:
    "You mentioned 'exams'. While it is important to talk about the importance of mistakes and revisions, as it relates to examinations, it may also be beneficial to touch on the variety of reasons students perform poorly. If you haven't already, feel free to mention things like testing anxiety and lack of preparation in previous classes. In addition, don’t forget to include the types of strategies that students can use to improve their readiness for tests–including revisions, peer tutoring, meeting with you individually etc",
  test: "You mentioned 'test'. While it is important to talk about the importance of mistakes and revisions, as it relates to examinations, it may also be beneficial to touch on the variety of reasons students perform poorly. If you haven't already, feel free to mention things like testing anxiety and lack of preparation in previous classes. In addition, don’t forget to include the types of strategies that students can use to improve their readiness for tests–including revisions, peer tutoring, meeting with you individually etc",
  tests:
    "You mentioned 'tests'. While it is important to talk about the importance of mistakes and revisions, as it relates to examinations, it may also be beneficial to touch on the variety of reasons students perform poorly. If you haven't already, feel free to mention things like testing anxiety and lack of preparation in previous classes. In addition, don’t forget to include the types of strategies that students can use to improve their readiness for tests–including revisions, peer tutoring, meeting with you individually etc",
  mistake:
    "You mentioned ‘mistake’. This is super important as making mistakes is necessary to student growth. It might be helpful to mention that you also make mistakes and/or have made plenty of math mistakes in the past. If you haven’t already, be sure to also mention that when a student makes a mistake it not only helps them learn and grow, but also can assist you with knowing how to change your teaching strategies so the information can be more clear. Mistakes are also an opportunity for revision, asking questions, and improving.",
  mistakes:
    "You mentioned ‘mistakes’. This is super important as making mistakes is necessary to student growth. It might be helpful to mention that you also make mistakes and/or have made plenty of math mistakes in the past. If you haven’t already, be sure to also mention that when a student makes a mistake it not only helps them learn and grow, but also can assist you with knowing how to change your teaching strategies so the information can be more clear. Mistakes are also an opportunity for revision, asking questions, and improving.",
  misstep:
    "You mentioned ‘misstep’. This is super important as making mistakes is necessary to student growth. It might be helpful to mention that you also make mistakes and/or have made plenty of math mistakes in the past. If you haven’t already, be sure to also mention that when a student makes a mistake it not only helps them learn and grow, but also can assist you with knowing how to change your teaching strategies so the information can be more clear. Mistakes are also an opportunity for revision, asking questions, and improving.",
  missteps:
    "You mentioned ‘missteps’. This is super important as making mistakes is necessary to student growth. It might be helpful to mention that you also make mistakes and/or have made plenty of math mistakes in the past. If you haven’t already, be sure to also mention that when a student makes a mistake it not only helps them learn and grow, but also can assist you with knowing how to change your teaching strategies so the information can be more clear. Mistakes are also an opportunity for revision, asking questions, and improving.",
  succeed:
    "You mentioned the word ‘succeed’. When you use these terms, make sure that you are using them in a context that talks about mastery of a specific skill. If you discuss being successful in the course or mastering math, broadly, make sure that is contextualized so it doesn't seem like you're imply you can get to a point where you are ‘good’ or ‘bad’ at math or ‘good’ or ‘bad,’ as it relates to this course because of your grades. Remember, the goal is to focus on overall improvement, mastery of skills, and of all students’ ability to understand the material overtime. Don’t hesitate to mention specific things that you or the class culture will/can do in order to support a student in receiving their full potential as it relates to math.",
  master:
    "You mentioned the word ‘master’. When you use these terms, make sure that you are using them in a context that talks about mastery of a specific skill. If you discuss being successful in the course or mastering math, broadly, make sure that is contextualized so it doesn't seem like you're imply you can get to a point where you are ‘good’ or ‘bad’ at math or ‘good’ or ‘bad,’ as it relates to this course because of your grades. Remember, the goal is to focus on overall improvement, mastery of skills, and of all students’ ability to understand the material overtime. Don’t hesitate to mention specific things that you or the class culture will/can do in order to support a student in receiving their full potential as it relates to math.",
  mastery:
    "You mentioned the word ‘mastery’. When you use these terms, make sure that you are using them in a context that talks about mastery of a specific skill. If you discuss being successful in the course or mastering math, broadly, make sure that is contextualized so it doesn't seem like you're imply you can get to a point where you are ‘good’ or ‘bad’ at math or ‘good’ or ‘bad,’ as it relates to this course because of your grades. Remember, the goal is to focus on overall improvement, mastery of skills, and of all students’ ability to understand the material overtime. Don’t hesitate to mention specific things that you or the class culture will/can do in order to support a student in receiving their full potential as it relates to math.",
  improvement:
    "You mentioned the word ‘improvement’. This is great because you are focusing on the ability of the students to learn material overtime and try new strategies to understand information more deeply–especially based on revising mistakes and asking questions. If you haven’t already, please include that while many students initially struggle in the course, and improve overtime, all students belong in your class and that you are excited to have them!",
  improve:
    "You mentioned the word ‘improve’. This is great because you are focusing on the ability of the students to learn material overtime and try new strategies to understand information more deeply–especially based on revising mistakes and asking questions. If you haven’t already, please include that while many students initially struggle in the course, and improve overtime, all students belong in your class and that you are excited to have them!",
  "good at math":
    "You have mentioned that some students feel they aren’t “good at math”. This is great because it is important to dispel this myth. All students are capable of learning all topics. If you haven’t already, feel free to add the specific ways that you will support students in changing or navigating these feelings. If you haven’t already, try to move away from any framing related to ideas of being ‘successful’ or ‘not successful’ in the class; this is very similar to the idea of being a “good math person.” Are there any other reasons why a person may feel hesitant about taking a math class? Might you, perhaps, include them along with the myth of the “math person.”",
  "math person":
    "You have mentioned that some students feel they aren’t a “math person”. This is great because it is important to dispel this myth. All students are capable of learning all topics. If you haven’t already, feel free to add the specific ways that you will support students in changing or navigating these feelings. If you haven’t already, try to move away from any framing related to ideas of being ‘successful’ or ‘not successful’ in the class; this is very similar to the idea of being a “good math person.” Are there any other reasons why a person may feel hesitant about taking a math class? Might you, perhaps, include them along with the myth of the “math person.”",
  smart:
    "You mentioned “smart”. Remember any insinuations that there is such a thing as a naturally “smart” student or parent could be harmful to the student in your class. If you haven’t already, try adjusting your framing to highlight students’ increasing capacity to learn, understand, and/or achieve mastery over material.",
  smartest:
    "You mentioned “smartest”. Remember any insinuations that there is such a thing as a naturally “smart” student or parent could be harmful to the student in your class. If you haven’t already, try adjusting your framing to highlight students’ increasing capacity to learn, understand, and/or achieve mastery over material.",
  score:
    "You mentioned ‘score’. It is beneficial to highlight that grades are not the most important thing about an exam; an exam is a snapshot of present material. However, insinuating that dissatisfaction with grades is the only reason that a student might/should want to revise their tests could be harmful. Try including the reality that a student may want to revise because they didn’t understand the material, was having a bad day on the day of the test, realized they prepared incorrectly etc. Additionally, if you only allow students to revise if they get below a 70, ask yourself why. Are you focusing on grades as a marker of mastery or intelligence or are you focused on improvement? ",
  scores:
    "You mentioned ‘scores’. It is beneficial to highlight that grades are not the most important thing about an exam; an exam is a snapshot of present material. However, insinuating that dissatisfaction with grades is the only reason that a student might/should want to revise their tests could be harmful. Try including the reality that a student may want to revise because they didn’t understand the material, was having a bad day on the day of the test, realized they prepared incorrectly etc. Additionally, if you only allow students to revise if they get below a 70, ask yourself why. Are you focusing on grades as a marker of mastery or intelligence or are you focused on improvement? ",
  grade:
    "You mentioned ‘grade’. It is beneficial to highlight that grades are not the most important thing about an exam; an exam is a snapshot of present material. However, insinuating that dissatisfaction with grades is the only reason that a student might/should want to revise their tests could be harmful. Try including the reality that a student may want to revise because they didn’t understand the material, was having a bad day on the day of the test, realized they prepared incorrectly etc. Additionally, if you only allow students to revise if they get below a 70, ask yourself why. Are you focusing on grades as a marker of mastery or intelligence or are you focused on improvement? ",
  grades:
    "You mentioned ‘grades’. It is beneficial to highlight that grades are not the most important thing about an exam; an exam is a snapshot of present material. However, insinuating that dissatisfaction with grades is the only reason that a student might/should want to revise their tests could be harmful. Try including the reality that a student may want to revise because they didn’t understand the material, was having a bad day on the day of the test, realized they prepared incorrectly etc. Additionally, if you only allow students to revise if they get below a 70, ask yourself why. Are you focusing on grades as a marker of mastery or intelligence or are you focused on improvement? ",
  challenge:
    "You mentioned the word ‘challenge’. Make sure that when you are using this word it is paired with the affirmation that the challenges can be overcome. Perhaps, provide a couple of strategies that can be used to navigate these difficulties if you haven't already (ie peer tutoring, practice problem sets etc). If you haven't already, this is a good place to mention that while the beginning of the course may be difficult, the students belong in the class. ",
  challenges:
    "You mentioned the word ‘challenges’. Make sure that when you are using this word it is paired with the affirmation that the challenges can be overcome. Perhaps, provide a couple of strategies that can be used to navigate these difficulties if you haven't already (ie peer tutoring, practice problem sets etc). If you haven't already, this is a good place to mention that while the beginning of the course may be difficult, the students belong in the class. ",
  difficult:
    "You mentioned the word ‘difficult’. Make sure that when you are using this word it is paired with the affirmation that the challenges can be overcome. Perhaps, provide a couple of strategies that can be used to navigate these difficulties if you haven't already (ie peer tutoring, practice problem sets etc). If you haven't already, this is a good place to mention that while the beginning of the course may be difficult, the students belong in the class. ",
  question:
    "You mentioned the word ‘question’. That is great because when students feel more comfortable asking questions, they feel more comfortable making mistakes and figuring out how to learn from them. If you haven’t already, highlight the reasons why you feel asking questions–even questions that they think are silly– are important (ie is useful for you and their peers who may be too shy to ask, it helps you understand what you need to spend more time focusing on etc). Also, provide more than one way that they can ask a question (ie in office hours, via email, on google meets, anonymously etc).",
  questions:
    "You mentioned the word ‘question’. That is great because when students feel more comfortable asking questions, they feel more comfortable making mistakes and figuring out how to learn from them. If you haven’t already, highlight the reasons why you feel asking questions–even questions that they think are silly– are important (ie is useful for you and their peers who may be too shy to ask, it helps you understand what you need to spend more time focusing on etc). Also, provide more than one way that they can ask a question (ie in office hours, via email, on google meets, anonymously etc).",
  revise:
    "You mentioned the word ‘revise’. Make sure that you clearly express your policy in relation to this and describe your reasoning behind allowing this practice.",
  resubmit:
    "You mentioned the word ‘resubmit’. Make sure that you clearly express your policy in relation to this and describe your reasoning behind allowing this practice.",
  redo: "You mentioned the word ‘redo’. Make sure that you clearly express your policy in relation to this and describe your reasoning behind allowing this practice.",
};
